# Site
languages: ["en", "ru"]
repository: sergeiosipov/sergeiosipov.com
favicon: images/favicon.ico

# Personal info
name: Sergei Osipov
title: Leading Financial Analyst
email: sergei.osipov@phystech.edu
website: www.sergeiosipov.com

# Social links
github_username:  sergeiosipov
linkedin_username: sergei-osipov
# twitter_username: ***
# stackoverflow_username: "nnnnnnnn"
# dribbble_username: ***
# facebook_username: ***
# flickr_username: ***
# instagram_username: ***
# xing_username: ***
# pinterest_username: ***
# youtube_username: ***
# orcid_username: 0000-0000-0000-0000
additional_links:
- title: telegram_username
  icon: fa-telegram
  url: https://t.me/sergeiosipov
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/sergeiosipov.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sergei and I'm a leading financial analyst. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>MS Office</mark>, <mark>Python</mark>, <mark>QlikView</mark> and <mark>MSSQL</mark>

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in finance and data analysis some of my other interests and hobbies are:
   - Working-out
   - Playing the guitar
   - Drawing

# Footer
footer_show_references: true

# Build settings
#theme: modern-resume-theme # (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme # (Use this if you are hosting your resume on GitHub)

darkmode: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
