# Site
repository: sergeiosipov/sergeiosipov.com
favicon: images/favicon.ico

# Personal info
name: Sergei Osipov
title: Leading Financial Analyst
email: sergei.osipov@phystech.edu
website: www.sergeiosipov.com

# Social links
# twitter_username: facespics
github_username:  sergeiosipov
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sergei-osipov
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sergei and I'm a leading financial analyst. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>MS Office</mark>, <mark>Python</mark>, <mark>QlikView</mark> and <mark>MSSQL</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in finance and data analysis some of my other interests and hobbies are:
   - Guitar
   - Powerlifting
   - Drawing
# link example: - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

# darkmode: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
